spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-dev-config
---
spring:
  profiles: test
  application:
    name: microservicecloud-test-config
